### ISSUE TITLE
The update-check doesn't find the version font pack-free should have

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix-fontpack-free#1]
I think the image is pretty self-explanatory. 
![bildschirmfoto 2018-12-09 um 14 55 40](https://user-images.githubusercontent.com/1153741/49699661-37a50400-fbd4-11e8-9d0e-ec8fa203ef4a.png)

**Comment by raphaelm** [comment]
Ah, I see why, we'll fix that soon enough!
